<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>Microsoft.StateKeeper.Samples</RootNamespace>
    <NoWarn>$(NoWarn);CA2007</NoWarn>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Microsoft.StateKeeper\Microsoft.StateKeeper.csproj" />
  </ItemGroup>

</Project>
